name: Build Pro APK
on:
  push:
    branches: [ main ] # سيبدأ البناء فور رفع أي ملف

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Ionic & Capacitor
        run: npm install -g @ionic/cli @capacitor/core @capacitor/cli

      - name: Create Dummy Web Assets
        run: mkdir www && touch www/index.html

      - name: Add Android Platform
        run: npx cap add android

      - name: Build Android App
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Send APK to Telegram
        run: |
          APK_PATH=$(find android/app/build/outputs/apk/debug/ -name "*.apk")
          curl -F document=@"$APK_PATH" "https://api.telegram.org/bot7915586739:AAEBKLRjDgB0sckmtIUIbBrl12C86ebqmy4/sendDocument?chat_id=YOUR_CHAT_ID"
